@host = http://localhost:4000

### test home
GET {{host}}/

### todos creation
POST {{host}}/todos
Content-Type: application/json

< ./src/fixtures/todos.json

### todos listing
GET {{host}}/todos

### empty db
POST {{host}}/dump