@host = http://localhost:3000

### test home
GET {{host}}/

### Ville creation
POST {{host}}/villes
Content-Type: application/json

< ./src/fixtures/villes.json

### Ville listing
GET {{host}}/villes

### empty db
POST {{host}}/dump